services:
  app:
    image: mysociety/la_emissions_data:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/la_emissions_data      
    volumes:
      - ./:/workspaces/la_emissions_data/